name: Bug report
description: Report a problem with ReactaForm
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug clearly
    validations:
      required: true
      