import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "React Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/reactaform.svg" />
        <link rel="apple-touch-icon" href="/reactaform.svg" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#0a84ff" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
