
export const dimensionUnitsMap: Record<string, string[]> = {
  length: ["m", "cm", "mm", "km", "in", "ft", "yd", "mi"],
  area: ["m^2", "cm^2", "mm^2", "in^2", "ft^2", "yd^2", "ha", "ac"],
  volume: ["L", "m^3", "cm^3", "mL", "in^3", "ft^3", "yd^3"],
  weight: ["kg", "g", "mg", "ton", "lb", "oz"],
  time: ["m", "s", "h", "ms", "d"],
  temperature: ["celsius", "fahrenheit", "kelvin"],
  angle: ["deg", "rad", "gradian", "rev", "minute", "second"],
};

// Friendly display names for units (per-dimension) used for labels in UI dropdowns
export const dimensionUnitDisplayMap: Record<
  string,
  Record<string, { name: string; shortName: string }>
> = {
  length: {
    mm: { name: "Millimeter (mm)", shortName: "mm" },
    cm: { name: "Centimeter (cm)", shortName: "cm" },
    m: { name: "Meter (m)", shortName: "m" },
    km: { name: "Kilometer (km)", shortName: "km" },
    in: { name: "Inch (in)", shortName: "in" },
    ft: { name: "Foot (ft)", shortName: "ft" },
    yd: { name: "Yard (yd)", shortName: "yd" },
    mi: { name: "Mile (mi)", shortName: "mi" },
  },
  area: {
    "mm^2": { name: "Square millimeter (mm²)", shortName: "mm²" },
    "m^2": { name: "Square meter (m²)", shortName: "m²" },
    "cm^2": { name: "Square centimeter (cm²)", shortName: "cm²" },
    "in^2": { name: "Square inch (in²)", shortName: "in²" },
    "ft^2": { name: "Square foot (ft²)", shortName: "ft²" },
    "yd^2": { name: "Square yard (yd²)", shortName: "yd²" },
    ha: { name: "Hectare (ha)", shortName: "ha" },
    ac: { name: "Acre (ac)", shortName: "ac" },
  },
  volume: {
    "cm^3": { name: "Cubic centimeter (cm³)", shortName: "cm³" },
    "m^3": { name: "Cubic meter (m³)", shortName: "m³" },
    L: { name: "Liter (L)", shortName: "L" },
    mL: { name: "Milliliter (mL)", shortName: "mL" },
    "in^3": { name: "Cubic inch (in³)", shortName: "in³" },
    "ft^3": { name: "Cubic foot (ft³)", shortName: "ft³" },
    "yd^3": { name: "Cubic yard (yd³)", shortName: "yd³" },
  },
  weight: {
    mg: { name: "Milligram (mg)", shortName: "mg" },
    g: { name: "Gram (g)", shortName: "g" },
    kg: { name: "Kilogram (kg)", shortName: "kg" },
    ton: { name: "Ton (t)", shortName: "ton" },
    lb: { name: "Pound (lb)", shortName: "lb" },
    oz: { name: "Ounce (oz)", shortName: "oz" },
  },
  time: {
    s: { name: "Second (s)", shortName: "s" },
    m: { name: "Minute (m)", shortName: "m" },
    h: { name: "Hour (h)", shortName: "h" },
    ms: { name: "Millisecond (ms)", shortName: "ms" },
    d: { name: "Day (d)", shortName: "d" },
  },
  temperature: {
    celsius: { name: "Celsius (°C)", shortName: "°C" },
    fahrenheit: { name: "Fahrenheit (°F)", shortName: "°F" },
    kelvin: { name: "Kelvin (K)", shortName: "K" },
  },
  angle: {
    deg: { name: "Degree (°)", shortName: "°" },
    rad: { name: "Radian (rad)", shortName: "rad" },
    gradian: { name: "Gradian", shortName: "gradian" },
    rev: { name: "Revolution (rev)", shortName: "rev" },
    minute: { name: "Arcminute (′)", shortName: "minute" },
    second: { name: "Arcsecond (″)", shortName: "second" },
  },
};

export const dimensonUnitFactorsMap: Record<string, Record<string, number>> = {
  length: {
    mm: 1000,
    cm: 100,
    m: 1,
    km: 0.001,
    in: 100 / 2.54,
    ft: 100 / (2.54 * 12),
    yd: 100 / (2.54 * 36),
    mi: 1 / 1609.344,
  },
  area: {
    "m²": 1.0,
    "mm²": 1000000,
    "cm²": 10000,
    "km²": 1 / 1000000,
    "in²": (100 / 2.54) ** 2,
    "ft²": (100 / (2.54 * 12)) ** 2,
    "yd²": (100 / (2.54 * 36)) ** 2,
    ha: 1 / 10000,
    ac: 1 / 4046.8564224,
  },
  volume: {
    "cm³": 1000000,
    "m³": 1.0,
    L: 1.0,
    mL: 1000000,
    "in³": (100 / 2.54) ** 3,
    "ft³": (100 / (2.54 * 12)) ** 3,
    "yd³": (100 / (2.54 * 36)) ** 3,
  },
  weight: {
    mg: 1000000,
    g: 1000,
    kg: 1,
    t: 0.001,
    lb: 1 / 0.45359237,
    oz: 1 / 0.028349523125,
  },
  time: {
    ms: 1000,
    s: 1,
    min: 1 / 60,
    h: 1 / 3600,
    d: 1 / 86400,
  },
  temperature: {
    "°C": 1,
    "°F": 33.8,
    K: 274.15,
  },
  angle: {
    "°": 1,
    rad: Math.PI / 180,
    gon: 10 / 9,
    rev: 1 / 360,
    "'": 60,
    '"': 3600,
  },
};
